http:
  port: ${PORT:-8080}
apiEndpoints:
  auth:
    host: localhost
    paths: '/auth/*'
  apiA:
    host: localhost
    paths: ['/apiA', '/apiA/*']
  apiB:
    host: localhost
    paths: ['/apiB', '/apiB/*']
serviceEndpoints:
  auth:
    url: 'http://localhost:${PORT_AUTH:-8081}'
  apiA:
    url: 'http://localhost:${PORT_API_A:-8082}'
  apiB:
    url: 'http://localhost:${PORT_API_B:-8083}'
policies:
  - auth
  - proxy
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - proxy:
        - action:
            serviceEndpoint: auth
  apiA:
    apiEndpoints:
      - apiA
    policies:
      - auth:
        - action:
            service: 'apiA'
      - proxy:
        - action:
            serviceEndpoint: apiA
  apiB:
    apiEndpoints:
      - apiB
    policies:
      - auth:
        - action:
            service: 'apiB'
      - proxy:
        - action:
            serviceEndpoint: apiB
